### ISSUE TITLE
1.3f Bug

### ISSUE THREAD

**Issue by m1zark** [Buuz135/ExtraChat#18]
Using 1.3f. Formatting now works, but its not showing the player names. Tags work as does everything else, its just not showing the player name, all I see is [] in chat.

**Comment by Buuz135** [comment]
Are you using spongy?

**Comment by m1zark** [comment]
No I'm not.

**Comment by Buuz135** [comment]
Can you try this version? http://buuz135.party:8080/job/ExtraChat-DEV/

**Comment by m1zark** [comment]
DEV version doesn't work either. Also just noticed the filter isn't working either, blacklisted words are still showing in chat.

**Comment by Buuz135** [comment]
Ooops, it compiled wrong try now http://buuz135.party:8080/job/ExtraChat-DEV/

**Comment by m1zark** [comment]
Well player names are showing now so that's a plus. The word filter isn't working though, but from what I've read I'm guessing your working on a new way to handle that so all good.

**Comment by Buuz135** [comment]
A new temp way it's word-word, are you using word:word?

**Comment by m1zark** [comment]
I mean its not filtering anything, even single words.

**Comment by Buuz135** [comment]
In the config do you put the words like word1-word2 or word1:word2

**Comment by m1zark** [comment]
Oh ok that works... I was using comas to separate the words. Continue with new features lol.
