### ISSUE TITLE
[Meta] Releases are not tagged in Git

### ISSUE THREAD

**Issue by Phroa** [Buuz135/ExtraChat#20]
http://git-scm.com/book/en/v2/Git-Basics-Tagging

You can retroactively apply tags and they'll show up in GitHub when you push them, don't worry.

Also, check out http://semver.org. It's a fabulous scheme. (Of course, it's up to you how to version things. `1.3g` is perfectly acceptable if you keep them consistent. Don't change version numbers you've already released in the past, though ^^)

**Comment by Buuz135** [comment]
I will try it :
