### ISSUE TITLE
[Suggestion] Add private message support

### ISSUE THREAD

**Issue by modwizcode** [Buuz135/ExtraChat#21]
Adding a style for private messages (and implementing them into the logger) would be a great feature. I can't tell you how many times having that extra bit of logging has been helpful to resolve a serious server issue.

The stylized formatting of private messages would reduce the need to depend on a second chat plugin for a small feature.

**Comment by Buuz135** [comment]
I have planed that and a mail system for next version but I didn't think about adding it to the logger. Currently it loggs all comands(not published)

**Comment by modwizcode** [comment]
The next version logs all commands?

**Comment by Buuz135** [comment]
Yes, even join, quit and death messages.

**Comment by modwizcode** [comment]
Great, I was gonna make my own chat plugin to integrate all these features but it seems I won't have too.

**Comment by Buuz135** [comment]
If you have more suggestions don't be scared to leave them here :D

**Comment by Buuz135** [comment]
Added in 1.4 :D
