### ISSUE TITLE
Chat Duplication - Switching Channels

### ISSUE THREAD

**Issue by Rentai** [Buuz135/ExtraChat#35]
I have been testing out the latest version of Extra chat on the recommended sponge 472.
Upon testing it out, I have made eleven channels, not including the default global. [Local was erased].
Upon server restart, I was testing through the channels to make sure they worked, at this time realizing that when switching out of the channels, messages were duplicating. 

For example:
Speaking in global upon logging in = Single Chat Output
Switch to a channel = 1 output within that channels chat
Switch back to global = Doubled Chat
Switch to a channel = 1 output within that channel still
Switch back to global = Tripled Chat

Screen Captures:
https://gyazo.com/28334168a56751c063cf7ef51a1eb05b
https://gyazo.com/debf4aaa1714e722d7c60033f17b750a
http://gyazo.com/55e8b0edcf3445f3a0baa65336bc8909

If needed:
Config:
http://pastebin.com/jm09rYNq
Chats:
http://pastebin.com/kb6qQYa3

**Comment by Buuz135** [comment]
Are you using /ch join to speak in a channel?

**Comment by Rentai** [comment]
Yes, I am using /ch join {name} as it makes more sense to me.
Also, if you are in a ch and select to quit {join/talk/quit} I believe quit with the last one, you are put.. nowhere? You simply cant speak in chat at all.
