### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rnateh** [Buuz135/ExtraChat#40]
How does one do multiple auto broadcasts. I can only get one to work in config. Can you give me a example of a config that has two?

**Comment by Buuz135** [comment]
[
  {
    "broadcast": "Hi this is a broadcast, welcome to the server.",
    "clickEvent": {
      "openURL": "https:www.google.com",
      //Optional
      "suggestCommand": "/me hi",
      //Optional
      "runCommand": "/me dances"
      //Optional
    },
    "hoverText": "This texts shows up when hovering the broadcast"
    //Optional
  },
{
    "broadcast": "Hi this is a broadcast, welcome to the server.",
    "clickEvent": {
      "openURL": "https:www.google.com",
      //Optional
      "suggestCommand": "/me hi",
      //Optional
      "runCommand": "/me dances"
      //Optional
    },
    "hoverText": "This texts shows up when hovering the broadcast"
    //Optional
  }

]

**Comment by Buuz135** [comment]
Separated by commas

**Comment by rnateh** [comment]
Fixed, thanks.
