### ISSUE TITLE
Last Question

### ISSUE THREAD

**Issue by rnateh** [Buuz135/ExtraChat#41]
How does one remove the optional stuff without breaking the code?

**Comment by Buuz135** [comment]
If it is optional you dont need to put it there.

**Comment by rnateh** [comment]
So if anyone clicks it does it check if they have permission to do /me or does it just make them do it. For if it makes them do it I need to make sure to delete that (attempted earlier but broke code).

**Comment by Buuz135** [comment]
Yeah, It runs the command as he would do it, it's not runned inside the code.

**Comment by rnateh** [comment]
Alright, I'll see if I Can remove it later again. Thanks.
